### ISSUE TITLE
How can i get the texture ?

### ISSUE THREAD

**Issue by badboy-tian** [asinesio/cocos2d-PRKit#11]
Hello, sir, i want save the lastest texture to resource file. how can i do ?

**Comment by asinesio** [comment]
If you're looking for the actual graphic to be exported to another system, try using CCRenderTexture, adding a PRFilledPolygon, and then getting the resulting pixels out of the CCRenderTexture and saving to a file.  I haven't tested it, but that should work.

If you're simply looking to re-create the PRFilledPolygon, you could just save the values used to create the polygon (either in NSUserDefaults, or in a plist, or in some other file) and then re-load those values and re-initialize the object just like you did the first time.
