### ISSUE TITLE
PRFilledPolygon's initWithPoints shouldn't return an autoreleased object

### ISSUE THREAD

**Issue by proth** [asinesio/cocos2d-PRKit#2]
init methods never return autoreleased objects in obj-c.

```
initWithPoints: (NSArray *) polygonPoints andTexture: (CCTexture2D *) fillTexture
```

returns an autoreleades PRFilledPolygon while

```
initWithPoints:(NSArray *)polygonPoints andTexture:(CCTexture2D *)fillTexture usingTriangulator: (id<PRTriangulator>) polygonTriangulator
```

does not.

**Comment by asinesio** [comment]
No, it doesn't -- it returns a filled polygon that has an autoreleased triangulator.  The polygon itself is not autoreleased.
