### ISSUE TITLE
textures do not display properly with retina display

### ISSUE THREAD

**Issue by jwstrav** [asinesio/cocos2d-PRKit#4]
PRFilledPolygon sprites are drawn much too small when running on the retina display.  This appears to be due to the fact that cocos2d scales things by the CC_CONTENT_SCALE_FACTOR and PRKit is currently not doing the same.  I'm running with the following patch in place which fixes the issue:

```
--- PRFilledPolygon.m
+++ PRFilledPolygon.m
@@ -67,7 +67,7 @@
     textureCoordinates = (CGPoint *) malloc(sizeof(CGPoint) * areaTrianglePointCount);

     for (int i = 0; i < areaTrianglePointCount; i++) {
-        areaTrianglePoints[i] = [[triangulatedPoints objectAtIndex:i] CGPointValue];
+        areaTrianglePoints[i] = ccpMult([[triangulatedPoints objectAtIndex:i] CGPointValue], CC_CONTENT_SCALE_FACTOR());
     }

     [self calculateTextureCoordinates];
```

**Comment by asinesio** [comment]
This is fixed in 0.3. Thanks for the patch and the issue request.
