### ISSUE TITLE
Problem with Cocos2d 2.0

### ISSUE THREAD

**Issue by eunatch** [asinesio/cocos2d-PRKit#5]
I'm using PRKit with the new version of Cocos2d, and I'm getting EXC_BAD_ACCESS in PRFilledPolygon.m on the following line:
glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL); (in the draw method)

The texture is loaded correctly, and it works fine with the old version of Cocos2d.

So I assume the OpenGl version is the real problem, as the big difference with cocos2d 2.0 is that is uses OpenGLES 2.0.

But being a complete noob with OpenGL, I can't manage to make it work...

Any idea on how I could do that ?

**Comment by themindoverall** [comment]
Hello!

I wrote a simple little version of the draw method that works with OpenGL ES 2.0 and therefore cocos2d 2.0.

I think it should probably cache the shader program rather than loading it each draw call, but anyway, it's a start.

``` objective-c
-(void) draw {
    CCGLProgram *prog = [[CCShaderCache sharedShaderCache] programForKey:kCCShader_PositionTexture];

    ccGLBindTexture2D( [self.texture name] );

    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);

    //
    // Attributes
    //
    ccGLEnableVertexAttribs( kCCVertexAttribFlag_Position | kCCVertexAttribFlag_TexCoords );


    ccGLUseProgram(prog->program_);
    ccGLUniformModelViewProjectionMatrix( prog );
    glVertexAttribPointer(kCCVertexAttrib_Position, 2, GL_FLOAT, GL_FALSE, sizeof(CGPoint), areaTrianglePoints);
    glVertexAttribPointer(kCCVertexAttrib_TexCoords, 2, GL_FLOAT, GL_FALSE, sizeof(CGPoint), textureCoordinates);

    glDrawArrays(GL_TRIANGLES, 0, areaTrianglePointCount);
}
```

**Comment by bagusflyer** [comment]
I got a "GL_CLAMP_TO_EDGE should be used in NPOT dimensions" error for Cocos2d 2.0 (I'm using the new code in the above post. 

Does this mean in this version I must use power of two texture? (In 1.0, I use NPOT texture without no problem.)

Thanks

**Comment by Panajev** [comment]
It means that you should either use a POT texture or change the texture wrapping mode.

**Comment by Panajev** [comment]
One more thing. With Cocos2D 1.1 you do have to add a rootViewController, so you need to modify the AppDelegate to do so : 

``` objective-c
- (void) applicationDidFinishLaunching:(UIApplication*)application {

[...]

     [window setRootViewController:viewController];

[...]

}
```

With Cocos2D 2.0 you also need to take away the RootViewController and modify the main delegate accordingly (a lot has changed with regards to view handling in Cocos2D 2.0). I forked PRKit and I am converting the project to Cocos2D 2.0 (and ARC, iOS 5.0 SDK as deployment target, no more ARMv6 support, etc...).
Here is the link: https://github.com/Panajev/cocos2d-PRKit

**Comment by asinesio** [comment]
Fixed (thanks Panajev).
