### ISSUE TITLE
Portrait Issue

### ISSUE THREAD

**Issue by swankywu** [asinesio/cocos2d-PRKit#6]
When I use the portrait mode, 

 it aways shows error in line 155 in file PRFilledPolygon.m

this line ---->
glDrawArrays(GL_TRIANGLES, 0, areaTrianglePointCount);

**Comment by eunatch** [comment]
Hi !
I had the same kind of problem but it wasn't coming from the device orientation.

It seems a crash may occur with glDrawArray(), when GL_COLOR_ARRAY client state is enabled (and no color pointer is specified).
If you look closely at the draw method of PRFilledPolygon.m, this client state is enabled at the end of the method, but not disabled at the beginning.

Try disabling the GL_COLOR_ARRAY in the beginning of the draw method, using:

 glDisableClientState(GL_COLOR_ARRAY);

This worked for me.

**Comment by swankywu** [comment]
YES~, I also found it.  That works!

**Comment by balanbliss** [comment]
Thanks....this one helped me..

**Comment by asinesio** [comment]
This appears to be fixed with the cocos2d 2.0 changes (no more glEnableClientState()) command.  If not, please re-open and attach a patch.
