### ISSUE TITLE
Not works on MAC, cocos2d 2.0(stable release)

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [asinesio/cocos2d-PRKit#9]
Test project http://kamikazeua.narod.ru/prkit.zip 
It's draw nothing on MAC and all works ok on iOS.

**Comment by asinesio** [comment]
When did you check out PRKit?  Mac support was recently added by Panajev.  If you're using the latest, I'll take a closer look.

**Comment by Anywhere-Music-Player** [comment]
I'm using all latest. Also I send a couple of mails to Panajev, but he does not response to me..  Please take a look..

**Comment by Anywhere-Music-Player** [comment]
Also, I tried post here.... with no response  http://www.cocos2d-iphone.org/forum/topic/32495 
http://www.cocos2d-iphone.org/forum/topic/75076

**Comment by asinesio** [comment]
I was able to reproduce the Mac issue.  Hopefully fix coming soon.

**Comment by asinesio** [comment]
Fixed. Code was assuming `CGPoint` and `GLFloat` were the same size, so it wasn't working on 64 bit systems (e.g. Mac OS X).

**Comment by Panajev** [comment]
KAMIKAZEUA, sorry for not getting back to you for so long. As you can see from my contributions chart on GitHub, I have been kind of off the grids for a long time now. Short story: started a new job in early December, moved abroad, etc... I will go in more detail in a PM. Again, my apologies for what happened.

**Comment by Anywhere-Music-Player** [comment]
Panajev, 

nice to hear you back :) and congratulations with new job! 
However Issue is fixed by asinesio! Thanks a lot!

**Comment by Panajev** [comment]
One thing I am still slapping myself over for is that by turning on more and more warnings I could have figured this out earlier on... floating point conversions... :(.
